# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/fmabrouk/Documents/GitHub/DDS_FM_Transmitter_100Hz _DAC_2020/FM_Modulation_DAC/FM_Modulation.srcs/sources_1/ip/fm_mod_0_1/fm_mod_0.xci
# IP: The module: 'fm_mod_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/fmabrouk/Documents/GitHub/DDS_FM_Transmitter_100Hz _DAC_2020/FM_Modulation_DAC/FM_Modulation.srcs/sources_1/ip/fm_mod_0_1/fm_mod_c_addsub_v12_0_i0/fm_mod_c_addsub_v12_0_i0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fm_mod_c_addsub_v12_0_i0 || ORIG_REF_NAME==fm_mod_c_addsub_v12_0_i0} -quiet] -quiet

# IP: c:/Users/fmabrouk/Documents/GitHub/DDS_FM_Transmitter_100Hz _DAC_2020/FM_Modulation_DAC/FM_Modulation.srcs/sources_1/ip/fm_mod_0_1/fm_mod_c_addsub_v12_0_i1/fm_mod_c_addsub_v12_0_i1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fm_mod_c_addsub_v12_0_i1 || ORIG_REF_NAME==fm_mod_c_addsub_v12_0_i1} -quiet] -quiet

# IP: c:/Users/fmabrouk/Documents/GitHub/DDS_FM_Transmitter_100Hz _DAC_2020/FM_Modulation_DAC/FM_Modulation.srcs/sources_1/ip/fm_mod_0_1/fm_mod_c_counter_binary_v12_0_i0/fm_mod_c_counter_binary_v12_0_i0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fm_mod_c_counter_binary_v12_0_i0 || ORIG_REF_NAME==fm_mod_c_counter_binary_v12_0_i0} -quiet] -quiet

# IP: c:/Users/fmabrouk/Documents/GitHub/DDS_FM_Transmitter_100Hz _DAC_2020/FM_Modulation_DAC/FM_Modulation.srcs/sources_1/ip/fm_mod_0_1/fm_mod_dds_compiler_v6_0_i0/fm_mod_dds_compiler_v6_0_i0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fm_mod_dds_compiler_v6_0_i0 || ORIG_REF_NAME==fm_mod_dds_compiler_v6_0_i0} -quiet] -quiet

# IP: c:/Users/fmabrouk/Documents/GitHub/DDS_FM_Transmitter_100Hz _DAC_2020/FM_Modulation_DAC/FM_Modulation.srcs/sources_1/ip/fm_mod_0_1/fm_mod_dds_compiler_v6_0_i1/fm_mod_dds_compiler_v6_0_i1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fm_mod_dds_compiler_v6_0_i1 || ORIG_REF_NAME==fm_mod_dds_compiler_v6_0_i1} -quiet] -quiet

# IP: c:/Users/fmabrouk/Documents/GitHub/DDS_FM_Transmitter_100Hz _DAC_2020/FM_Modulation_DAC/FM_Modulation.srcs/sources_1/ip/fm_mod_0_1/fm_mod_fir_compiler_v7_2_i0/fm_mod_fir_compiler_v7_2_i0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fm_mod_fir_compiler_v7_2_i0 || ORIG_REF_NAME==fm_mod_fir_compiler_v7_2_i0} -quiet] -quiet

# IP: c:/Users/fmabrouk/Documents/GitHub/DDS_FM_Transmitter_100Hz _DAC_2020/FM_Modulation_DAC/FM_Modulation.srcs/sources_1/ip/fm_mod_0_1/fm_mod_fir_compiler_v7_2_i1/fm_mod_fir_compiler_v7_2_i1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fm_mod_fir_compiler_v7_2_i1 || ORIG_REF_NAME==fm_mod_fir_compiler_v7_2_i1} -quiet] -quiet

# IP: c:/Users/fmabrouk/Documents/GitHub/DDS_FM_Transmitter_100Hz _DAC_2020/FM_Modulation_DAC/FM_Modulation.srcs/sources_1/ip/fm_mod_0_1/fm_mod_mult_gen_v12_0_i0/fm_mod_mult_gen_v12_0_i0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fm_mod_mult_gen_v12_0_i0 || ORIG_REF_NAME==fm_mod_mult_gen_v12_0_i0} -quiet] -quiet

# IP: c:/Users/fmabrouk/Documents/GitHub/DDS_FM_Transmitter_100Hz _DAC_2020/FM_Modulation_DAC/FM_Modulation.srcs/sources_1/ip/fm_mod_0_1/fm_mod_mult_gen_v12_0_i1/fm_mod_mult_gen_v12_0_i1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fm_mod_mult_gen_v12_0_i1 || ORIG_REF_NAME==fm_mod_mult_gen_v12_0_i1} -quiet] -quiet

# IP: c:/Users/fmabrouk/Documents/GitHub/DDS_FM_Transmitter_100Hz _DAC_2020/FM_Modulation_DAC/FM_Modulation.srcs/sources_1/ip/fm_mod_0_1/fm_mod_mult_gen_v12_0_i2/fm_mod_mult_gen_v12_0_i2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fm_mod_mult_gen_v12_0_i2 || ORIG_REF_NAME==fm_mod_mult_gen_v12_0_i2} -quiet] -quiet

# XDC: c:/Users/fmabrouk/Documents/GitHub/DDS_FM_Transmitter_100Hz _DAC_2020/FM_Modulation_DAC/FM_Modulation.srcs/sources_1/ip/fm_mod_0_1/constrs/fm_mod.xdc
# XDC: The top module name and the constraint reference have the same name: 'fm_mod_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/fmabrouk/Documents/GitHub/DDS_FM_Transmitter_100Hz _DAC_2020/FM_Modulation_DAC/FM_Modulation.srcs/sources_1/ip/fm_mod_0_1/fm_mod_fir_compiler_v7_2_i0/constraints/fir_compiler_v7_2.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fm_mod_fir_compiler_v7_2_i0 || ORIG_REF_NAME==fm_mod_fir_compiler_v7_2_i0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/fmabrouk/Documents/GitHub/DDS_FM_Transmitter_100Hz _DAC_2020/FM_Modulation_DAC/FM_Modulation.srcs/sources_1/ip/fm_mod_0_1/fm_mod_fir_compiler_v7_2_i1/constraints/fir_compiler_v7_2.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fm_mod_fir_compiler_v7_2_i1 || ORIG_REF_NAME==fm_mod_fir_compiler_v7_2_i1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# IP: c:/Users/fmabrouk/Documents/GitHub/DDS_FM_Transmitter_100Hz _DAC_2020/FM_Modulation_DAC/FM_Modulation.srcs/sources_1/ip/fm_mod_0_1/fm_mod_0.xci
# IP: The module: 'fm_mod_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/fmabrouk/Documents/GitHub/DDS_FM_Transmitter_100Hz _DAC_2020/FM_Modulation_DAC/FM_Modulation.srcs/sources_1/ip/fm_mod_0_1/fm_mod_c_addsub_v12_0_i0/fm_mod_c_addsub_v12_0_i0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fm_mod_c_addsub_v12_0_i0 || ORIG_REF_NAME==fm_mod_c_addsub_v12_0_i0} -quiet] -quiet

# IP: c:/Users/fmabrouk/Documents/GitHub/DDS_FM_Transmitter_100Hz _DAC_2020/FM_Modulation_DAC/FM_Modulation.srcs/sources_1/ip/fm_mod_0_1/fm_mod_c_addsub_v12_0_i1/fm_mod_c_addsub_v12_0_i1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fm_mod_c_addsub_v12_0_i1 || ORIG_REF_NAME==fm_mod_c_addsub_v12_0_i1} -quiet] -quiet

# IP: c:/Users/fmabrouk/Documents/GitHub/DDS_FM_Transmitter_100Hz _DAC_2020/FM_Modulation_DAC/FM_Modulation.srcs/sources_1/ip/fm_mod_0_1/fm_mod_c_counter_binary_v12_0_i0/fm_mod_c_counter_binary_v12_0_i0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fm_mod_c_counter_binary_v12_0_i0 || ORIG_REF_NAME==fm_mod_c_counter_binary_v12_0_i0} -quiet] -quiet

# IP: c:/Users/fmabrouk/Documents/GitHub/DDS_FM_Transmitter_100Hz _DAC_2020/FM_Modulation_DAC/FM_Modulation.srcs/sources_1/ip/fm_mod_0_1/fm_mod_dds_compiler_v6_0_i0/fm_mod_dds_compiler_v6_0_i0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fm_mod_dds_compiler_v6_0_i0 || ORIG_REF_NAME==fm_mod_dds_compiler_v6_0_i0} -quiet] -quiet

# IP: c:/Users/fmabrouk/Documents/GitHub/DDS_FM_Transmitter_100Hz _DAC_2020/FM_Modulation_DAC/FM_Modulation.srcs/sources_1/ip/fm_mod_0_1/fm_mod_dds_compiler_v6_0_i1/fm_mod_dds_compiler_v6_0_i1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fm_mod_dds_compiler_v6_0_i1 || ORIG_REF_NAME==fm_mod_dds_compiler_v6_0_i1} -quiet] -quiet

# IP: c:/Users/fmabrouk/Documents/GitHub/DDS_FM_Transmitter_100Hz _DAC_2020/FM_Modulation_DAC/FM_Modulation.srcs/sources_1/ip/fm_mod_0_1/fm_mod_fir_compiler_v7_2_i0/fm_mod_fir_compiler_v7_2_i0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fm_mod_fir_compiler_v7_2_i0 || ORIG_REF_NAME==fm_mod_fir_compiler_v7_2_i0} -quiet] -quiet

# IP: c:/Users/fmabrouk/Documents/GitHub/DDS_FM_Transmitter_100Hz _DAC_2020/FM_Modulation_DAC/FM_Modulation.srcs/sources_1/ip/fm_mod_0_1/fm_mod_fir_compiler_v7_2_i1/fm_mod_fir_compiler_v7_2_i1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fm_mod_fir_compiler_v7_2_i1 || ORIG_REF_NAME==fm_mod_fir_compiler_v7_2_i1} -quiet] -quiet

# IP: c:/Users/fmabrouk/Documents/GitHub/DDS_FM_Transmitter_100Hz _DAC_2020/FM_Modulation_DAC/FM_Modulation.srcs/sources_1/ip/fm_mod_0_1/fm_mod_mult_gen_v12_0_i0/fm_mod_mult_gen_v12_0_i0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fm_mod_mult_gen_v12_0_i0 || ORIG_REF_NAME==fm_mod_mult_gen_v12_0_i0} -quiet] -quiet

# IP: c:/Users/fmabrouk/Documents/GitHub/DDS_FM_Transmitter_100Hz _DAC_2020/FM_Modulation_DAC/FM_Modulation.srcs/sources_1/ip/fm_mod_0_1/fm_mod_mult_gen_v12_0_i1/fm_mod_mult_gen_v12_0_i1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fm_mod_mult_gen_v12_0_i1 || ORIG_REF_NAME==fm_mod_mult_gen_v12_0_i1} -quiet] -quiet

# IP: c:/Users/fmabrouk/Documents/GitHub/DDS_FM_Transmitter_100Hz _DAC_2020/FM_Modulation_DAC/FM_Modulation.srcs/sources_1/ip/fm_mod_0_1/fm_mod_mult_gen_v12_0_i2/fm_mod_mult_gen_v12_0_i2.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fm_mod_mult_gen_v12_0_i2 || ORIG_REF_NAME==fm_mod_mult_gen_v12_0_i2} -quiet] -quiet

# XDC: c:/Users/fmabrouk/Documents/GitHub/DDS_FM_Transmitter_100Hz _DAC_2020/FM_Modulation_DAC/FM_Modulation.srcs/sources_1/ip/fm_mod_0_1/constrs/fm_mod.xdc
# XDC: The top module name and the constraint reference have the same name: 'fm_mod_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/fmabrouk/Documents/GitHub/DDS_FM_Transmitter_100Hz _DAC_2020/FM_Modulation_DAC/FM_Modulation.srcs/sources_1/ip/fm_mod_0_1/fm_mod_fir_compiler_v7_2_i0/constraints/fir_compiler_v7_2.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fm_mod_fir_compiler_v7_2_i0 || ORIG_REF_NAME==fm_mod_fir_compiler_v7_2_i0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/fmabrouk/Documents/GitHub/DDS_FM_Transmitter_100Hz _DAC_2020/FM_Modulation_DAC/FM_Modulation.srcs/sources_1/ip/fm_mod_0_1/fm_mod_fir_compiler_v7_2_i1/constraints/fir_compiler_v7_2.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fm_mod_fir_compiler_v7_2_i1 || ORIG_REF_NAME==fm_mod_fir_compiler_v7_2_i1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet
