# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/sysgen/fm_mod_clock.xdc

# XDC: imports/sysgen/fm_mod.xdc

# Block Designs: bd/fm_mod_bd/fm_mod_bd.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fm_mod_bd || ORIG_REF_NAME==fm_mod_bd} -quiet] -quiet

# IP: bd/fm_mod_bd/ip/fm_mod_bd_fm_mod_1_0/fm_mod_bd_fm_mod_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fm_mod_bd_fm_mod_1_0 || ORIG_REF_NAME==fm_mod_bd_fm_mod_1_0} -quiet] -quiet

# XDC: bd/fm_mod_bd/fm_mod_bd_ooc.xdc
