@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.2 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Wed Apr 15 18:13:47 -0700 2026
REM SW Build 3064766 on Wed Nov 18 09:12:45 MST 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
REM elaborate design
echo "xelab -wto e6362ae8ad8d4879b8aeb80b63e3e765 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L unisims_ver -L secureip --snapshot FM_Modulator_DAC_TopLevel_func_synth xil_defaultlib.FM_Modulator_DAC_TopLevel xil_defaultlib.glbl -log elaborate.log"
call xelab  -wto e6362ae8ad8d4879b8aeb80b63e3e765 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L unisims_ver -L secureip --snapshot FM_Modulator_DAC_TopLevel_func_synth xil_defaultlib.FM_Modulator_DAC_TopLevel xil_defaultlib.glbl -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
