@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Wed Apr 15 18:14:07 -0700 2026
REM SW Build 3064766 on Wed Nov 18 09:12:45 MST 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim FM_Modulator_DAC_TopLevel_func_synth -key {Post-Synthesis:sim_1:Functional:FM_Modulator_DAC_TopLevel} -tclbatch FM_Modulator_DAC_TopLevel.tcl -view C:/Users/fmabrouk/Documents/GitHub/DDS_FM_Transmitter_100Hz _DAC_2020/FM_Modulation_DAC/FM_Modulator_DAC_TopLevel_func_synth.wcfg -log simulate.log"
call xsim  FM_Modulator_DAC_TopLevel_func_synth -key {Post-Synthesis:sim_1:Functional:FM_Modulator_DAC_TopLevel} -tclbatch FM_Modulator_DAC_TopLevel.tcl -view C:/Users/fmabrouk/Documents/GitHub/DDS_FM_Transmitter_100Hz _DAC_2020/FM_Modulation_DAC/FM_Modulator_DAC_TopLevel_func_synth.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
