# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/fmabrouk/Documents/GitHub/DDS_FM_Transmitter_100Hz _DAC_2020/FM_Modulation_DAC/FM_Modulation.srcs/sources_1/ip/mult_gen/mult_gen.xci
# IP: The module: 'mult_gen' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/fmabrouk/Documents/GitHub/DDS_FM_Transmitter_100Hz _DAC_2020/FM_Modulation_DAC/FM_Modulation.srcs/sources_1/ip/mult_gen/mult_gen_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mult_gen'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/fmabrouk/Documents/GitHub/DDS_FM_Transmitter_100Hz _DAC_2020/FM_Modulation_DAC/FM_Modulation.srcs/sources_1/ip/mult_gen/mult_gen.xci
# IP: The module: 'mult_gen' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/fmabrouk/Documents/GitHub/DDS_FM_Transmitter_100Hz _DAC_2020/FM_Modulation_DAC/FM_Modulation.srcs/sources_1/ip/mult_gen/mult_gen_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mult_gen'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
